// <auto-generated />
namespace DoAn_LTWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeBrand_Id1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeBrand_Id1));
        
        string IMigrationMetadata.Id
        {
            get { return "202311291604128_removeBrand_Id1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
