// <auto-generated />
namespace DoAn_LTWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeUserIdRow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeUserIdRow));
        
        string IMigrationMetadata.Id
        {
            get { return "202312051559455_removeUserIdRow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
